### ISSUE TITLE
The code block translation is still broken

### ISSUE THREAD

**Issue by tbrowder** [antononcube/Raku-Markdown-Grammar#3] opened 2022-11-03 12:00 UTC
Given this in Markdown (the apostrophes represent backticks):

    '''json

This module still creates:

    =begin code json

which causes the pod to fail compilation by Raku.

The proper output for the line should be:

    =begin code :lang<json>

**Comment by antononcube** [comment] 2022-11-03 14:21
I cannot reproduce this:

![](https://i.imgur.com/W14imnn.png)

**Comment by tbrowder** [comment] 2022-11-04 01:14
Thanks, I'll look more closely...

**Comment by tbrowder** [comment] 2022-11-04 11:03
A better, complete example. Create a Raku program containing the following lines:

    use Markdown::Grammar;
    my $s = q:to/HERE/;
    '''json
    '''
    HERE
    my $p = from-markdown $s, to => 'pod6';
    say $p;

Call the program 'test.raku'. Run

   $ raku test.raku
    =begin pod
    =begin code json
    =end code
    =end pod

**Comment by antononcube** [comment] 2022-11-04 11:36
I still cannot reproduce the bug (with the most recent code of this repository.)
See the attached screenshot.

![](https://i.imgur.com/jxzwYwP.png)

**Comment by antononcube** [comment] 2022-11-05 17:33
Closing as fixed.

**Closed** 2022-11-05 17:33 UTC
